// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAppDepartment.DAL.Data.Context;

#nullable disable

namespace WebAppDepartment.DAL.Migrations
{
    [DbContext(typeof(DepartmentContext))]
    [Migration("20230428173412_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAppDepartment.DAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("double precision");

                    b.Property<int>("Evaluation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DepartmentSet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 27064.0,
                            Evaluation = 4,
                            Name = "Prodction"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 2706400.0,
                            Evaluation = 5,
                            Name = "R&D"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 270600.0,
                            Evaluation = 3,
                            Name = "Prodction"
                        });
                });

            modelBuilder.Entity("WebAppDepartment.DAL.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("EmployeeSet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "ali"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "mo"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Name = "fo"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "to"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Name = "do"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Name = "lo"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Name = "po"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Name = "al"
                        });
                });

            modelBuilder.Entity("WebAppDepartment.DAL.Employee", b =>
                {
                    b.HasOne("WebAppDepartment.DAL.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebAppDepartment.DAL.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
